### PR TITLE
fix vertex particle handling in graph.py

### PR DESCRIPTION
**Pull request by lcnbr**

### CODE REVIEW

**Comment by lcnbr** [comment]
Otherwise you arent actually using the vertex info ordering

**Comment by lcnbr** [comment]
I don't know what the orig_particle_vertex was used for.

**Review by ValentinHirschi — APPROVED** [review]
Indeed, thanks for identifying my typo!

**Review by ValentinHirschi — APPROVED** [review]
Thanks for fixing my typo!

**Review by GraDje13 — APPROVED** [review]

**Review by ValentinHirschi — CHANGES_REQUESTED** [review]
@lcnbr Indeed, I needed to loop over `vertex_particles` there.
you can then also remove this line altogether:

orig_vertex_particles = [v[0] for v in vertex_particles_per_edge]

**Review by ValentinHirschi — APPROVED** [review]
Perfect, thanks!

**Comment by lcnbr** [comment]
Now I think it is safe to merge

**Review by ValentinHirschi — APPROVED** [review]

**Pull request merged**
