### PR TITLE
Update to Symbolica 0.13 and spenso aind format

### PR DESCRIPTION
**Pull request by lcnbr**

### CODE REVIEW

**Review by ValentinHirschi — APPROVED** [review]
Maybe you can add the half-edge graph here already

**Comment by lcnbr** [comment]
Yep that is what I'm working on!

**Comment by lcnbr** [comment]
Shall we merge?

**Review by GraDje13 — APPROVED** [review]
Seems good to me!

**Comment by ValentinHirschi** [comment]
> Shall we merge?

In dev, yes!

**Comment by lcnbr** [comment]
> > Shall we merge?
> 
> In dev, yes!

This is dev..

**Pull request merged**
