### PR TITLE
Integrand

### PR DESCRIPTION
**Pull request by GraDje13**
Most important things seem to be fully worked out, so I will put it up for review :)

### CODE REVIEW

**Review by lcnbr — APPROVED** [review]
Everything looks good! HPC stuff is very configurable. The evaluate pipeline is also quite clear. 

The one thing I am a little less stoked on is the proliferation of serializable versions of structs. Maybe we should look into serde_with.

**Comment by ValentinHirschi** [comment]
The generation + launching looks good!

First a note to self: after something like a `launch` command is issued, I'd like the python logging to reflect that all commands and outputs are now from within the context of a CLI bound to the process output we launched from.
I'll try and cook up something like this in madsymbolic.

Second: the following startup line when integrating could be improved:
[ 2024-03-24 12:48:37,494 ] @_gammaloop.integrate INFO: gammaloop now integrates 'gamma_loop' over a top-level continuous 3-dimensional grid ...
by:

a) Making sure the name of the integrand given here (`gamma_loop`) reflect the process output, so something like `massless_triangle` or `massless_triangle.gamma_loop`.

b) Now that we have multiple sampling techniques and ability to turn on multichanneling or not, it'd be great if this line were to reveal which sampling we're using (and eventually integrator, though for now we only have havana, but it'd be future proof to put it in there as soon as the integrator itself is abstracted away) and also if multi-channeling is enabled and, if so, over how many channels.

**Comment by ValentinHirschi** [comment]
Also, I don't know about your system, but on mine `crtl+C` does not stop the integration.
I think we need explicit system interrupt listening for this.
For this, you can see how Ben implemented `check_interrupt` in `Symbolica` (https://reform.zulipchat.com/#narrow/stream/392700-functionality/topic/interrupt/near/420224289)

**Comment by ValentinHirschi** [comment]
The extra integration info is very much welcome:
```
[ 2024-03-24 12:48:57,515 ] @_gammaloop.evaluation_result INFO: |  average ltd expression evaluation time: 1 µs
[ 2024-03-24 12:48:57,515 ] @_gammaloop.evaluation_result INFO: |  average paramatrization time:           305 ns
[ 2024-03-24 12:48:57,515 ] @_gammaloop.evaluation_result INFO: |  total evaluation time:                  4 µs
[ 2024-03-24 12:48:57,515 ] @_gammaloop.evaluation_result INFO: |  evaluations in f64:                     100.00%
[ 2024-03-24 12:48:57,515 ] @_gammaloop.evaluation_result INFO: |  evaluations in f128:                    0.00%
[ 2024-03-24 12:48:57,515 ] @_gammaloop.evaluation_result INFO: |  nan evaluations:                        0.00%
```
But a bit verbose maybe, I'd go for a two-liner:
```
| timings | total: XXX param: YYY LTD: ZZZ
| evals | f64: XXX f128: YYY NaN: ZZZ (and also in light of later when they'll be cut, we should add) zeros: WWW
```

Ultimately we should really have a proper UI on the browser served live with gammaLoop, and with fancy visualisations and maybe even an SQL DB to store all our run results, incl. evolution across iterations and plots.
But that's all music for later (maybe when we'll tackle HPC support)

**Comment by GraDje13** [comment]
> Also, I don't know about your system, but on mine `crtl+C` does not stop the integration. I think we need explicit system interrupt listening for this. For this, you can see how Ben implemented `check_interrupt` in `Symbolica` (https://reform.zulipchat.com/#narrow/stream/392700-functionality/topic/interrupt/near/420224289)

You are right that `ctrl+C` does not stop the integration. I usually kill the process from htop if I need to. But having a working `ctrl+C` would be nice indeed. I'll look a bit more into how it can be done!

**Comment by lcnbr** [comment]
> > Also, I don't know about your system, but on mine `crtl+C` does not stop the integration. I think we need explicit system interrupt listening for this. For this, you can see how Ben implemented `check_interrupt` in `Symbolica` (https://reform.zulipchat.com/#narrow/stream/392700-functionality/topic/interrupt/near/420224289)
> 
> You are right that `ctrl+C` does not stop the integration. I usually kill the process from htop if I need to. But having a working `ctrl+C` would be nice indeed. I'll look a bit more into how it can be done!

see: https://pyo3.rs/v0.21.0-beta.0/faq#ctrl-c-doesnt-do-anything-while-my-rust-code-is-executing

**Comment by GraDje13** [comment]
> > > Also, I don't know about your system, but on mine `crtl+C` does not stop the integration. I think we need explicit system interrupt listening for this. For this, you can see how Ben implemented `check_interrupt` in `Symbolica` (https://reform.zulipchat.com/#narrow/stream/392700-functionality/topic/interrupt/near/420224289)
> > 
> > 
> > You are right that `ctrl+C` does not stop the integration. I usually kill the process from htop if I need to. But having a working `ctrl+C` would be nice indeed. I'll look a bit more into how it can be done!
> 
> see: https://pyo3.rs/v0.21.0-beta.0/faq#ctrl-c-doesnt-do-anything-while-my-rust-code-is-executing

Yeah I already found that, but it requires some additional gymnastics to get working with multithreading. I used the solution from https://stackoverflow.com/questions/62364030/keyboard-interrupt-from-python-does-not-abort-rust-function-pyo3 instead, it's essentially a one-liner in rust with the ctrlc crate.

**Comment by ValentinHirschi** [comment]
Also, `hyperqueue` pip seems to only support python being *exactly* 3.6 -.-....

https://pypi.org/project/hyperqueue/0.18.0/#files

@GraDje13 how did you install it? I also tried from source but it's annoyingly complicated on mac it seems due to some dirty LIBC dependency so that their recipe did not work for me.
How did you do it? In any case, I think using a meta-scheduler is great so we'll likely stick to it and if push comes to shove really ship our own fork of it in rust then :)

**Comment by GraDje13** [comment]
> Also, `hyperqueue` pip seems to only support python being _exactly_ 3.6 -.-....
> 
> https://pypi.org/project/hyperqueue/0.18.0/#files
> 
> @GraDje13 how did you install it? I also tried from source but it's annoyingly complicated on mac it seems due to some dirty LIBC dependency so that their recipe did not work for me. How did you do it? In any case, I think using a meta-scheduler is great so we'll likely stick to it and if push comes to shove really ship our own fork of it in rust then :)

Hmm strange, for me it seems to be installed through pip and working fine on python 3.11. The python API is not strictly necessary, we could also just use the executable version with some script, although for now it seemed very convenient.

**Comment by ValentinHirschi** [comment]
and for the crtl+c I checked that it works now! Would it possible to make it so that crtl+C yields back to Python so that it can output a summary of the integration thus far before exiting? I think it's possible if you escalate exceptions, but ok if too difficult nevermind.

**Comment by GraDje13** [comment]
> > > But maybe something for now that could be good is a minimal check-point system where the latest grid (really just an accumulator at this point with tropical sampling) is picked up if found and integration takes it from there (with a clear message from the user so that he's aware is restarting a run from a known point, and an option to the `integrate` command that forces it to start from scratch).
> > 
> > 
> > Good idea, I will try to implement something like this! I just realized, to do this properly, one needs to save the state of the random number generator as well. Which at the moment is the `MonteCarloRng` from Symbolica.
> > Alternatively, we could create a new MonteCarloRng at each iteration. Saving the state at each iteration then ensures reproducible runs and unbiased statistics.
> 
> If that can easily be done then sure! Otherwise, it's also ok to assume non-seed-fixing if runs get restarted I suppose.

I managed to do it by creating a new MonteCarloRng with the iteration as a seed on each iteration, perhaps in the future it would be nice to save the state of the random number generator, in terms of types it should be easy but of course the state is not public.

**Comment by GraDje13** [comment]
> and for the crtl+c I checked that it works now! Would it possible to make it so that crtl+C yields back to Python so that it can output a summary of the integration thus far before exiting? I think it's possible if you escalate exceptions, but ok if too difficult nevermind.

I can take another look at it, but most likely it will be non-trivial due to the multithreading.

**Comment by GraDje13** [comment]
I added a safeguard so that the user can not change the integration settings between stopping and resuming a run, since this could lead to crashes or incorrect results.

**Review by ValentinHirschi — APPROVED** [review]
After discussion with Mathijs and my recent changes, it should all be good pending tests passing!

**Review by lcnbr — APPROVED** [review]

**Review by ValentinHirschi — APPROVED** [review]

**Pull request merged**
